# Generated by Django 5.1.3 on 2024-12-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meja_biliar', '0002_alter_mejabiliar_options_mejabiliar_status_and_more'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durasi_sewa', models.PositiveIntegerField()),
                ('harga_meja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_menu', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meja_biliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meja_biliar.mejabiliar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesananMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesanan.pesanan')),
            ],
        ),
        migrations.AddField(
            model_name='pesanan',
            name='menu',
            field=models.ManyToManyField(through='pesanan.PesananMenu', to='menu.menu'),
        ),
    ]
