# Generated by Django 5.1.3 on 2024-12-04 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='menu',
        ),
        migrations.RenameField(
            model_name='pesanan',
            old_name='meja_biliar',
            new_name='meja',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='durasi_sewa',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='harga_meja',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='qty_menu',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='total_harga',
        ),
        migrations.AddField(
            model_name='pesanan',
            name='tanggal_pemesanan',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetailPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pesanan', to='pesanan.pesanan')),
            ],
        ),
        migrations.DeleteModel(
            name='PesananMenu',
        ),
    ]
