# Generated by Django 5.1.3 on 2024-12-04 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0002_remove_pesanan_menu_rename_meja_biliar_pesanan_meja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='durasi_pemesanan',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
