# Generated by Django 5.1.3 on 2024-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0003_pesanan_durasi_pemesanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='durasi_pemesanan',
        ),
        migrations.AddField(
            model_name='pesanan',
            name='durasi_meja',
            field=models.PositiveIntegerField(default=60, help_text='Durasi pemesanan dalam menit'),
        ),
    ]
