# Generated by Django 5.1.3 on 2024-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0004_remove_pesanan_durasi_pemesanan_pesanan_durasi_meja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='durasi_meja',
            field=models.PositiveIntegerField(default=1, help_text='Durasi pemesanan dalam jam'),
        ),
    ]
