# Generated by Django 5.1.3 on 2024-12-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0005_alter_pesanan_durasi_meja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
