# Generated by Django 5.1.3 on 2024-12-04 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0006_pesanan_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='waktu_pembuatan',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Waktu ketika pesanan dibuat'),
        ),
    ]
