# Generated by Django 5.1.3 on 2024-12-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0007_pesanan_waktu_pembuatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='waktu_pembuatan',
        ),
    ]
