# Generated by Django 5.1.3 on 2024-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0008_remove_pesanan_waktu_pembuatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='status',
            field=models.CharField(default='aktif', max_length=20),
        ),
    ]
