# Generated by Django 5.1.3 on 2024-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0009_pesanan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='is_send',
            field=models.BooleanField(default=True),
        ),
    ]
