# Generated by Django 5.1.3 on 2024-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0012_pesanan_waktu_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='notifikasi_dikirim',
            field=models.BooleanField(default=False),
        ),
    ]
