# Generated by Django 5.1.3 on 2024-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MejaBiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_meja', models.CharField(max_length=10, unique=True, verbose_name='Nomor Meja')),
                ('harga_siang', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Siang')),
                ('harga_malam', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Malam')),
            ],
            options={
                'verbose_name': 'Meja Biliar',
                'verbose_name_plural': 'Meja Meja Biliar',
            },
        ),
    ]
