# Generated by Django 5.1.3 on 2024-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meja_biliar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mejabiliar',
            options={},
        ),
        migrations.AddField(
            model_name='mejabiliar',
            name='status',
            field=models.CharField(choices=[('full', 'Full'), ('ada', 'Ada'), ('perbaikan', 'Perbaikan')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='mejabiliar',
            name='harga_malam',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mejabiliar',
            name='harga_siang',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mejabiliar',
            name='no_meja',
            field=models.CharField(max_length=20),
        ),
    ]
